# Generated by Django 3.2.10 on 2023-01-22 21:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=1024)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('apply_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('out_date', models.DateField()),
                ('status', models.CharField(max_length=25)),
                ('uni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorms.university')),
            ],
        ),
    ]
